### ISSUE TITLE
Drohnen erreichen 8. Wegpunkt bei 3. Map nicht

### ISSUE THREAD

**Issue by kelp-byte** [DronesTowerDefence/DTD#25]
Ich finde den Fehler nicht, ist irgendwo anders als bei der Map-Klasse glaub ich

**Comment by MokkaGnom** [comment]
Habe den Fehler gefunden!
Insgesamt hat sich die Drohne, auf dem Weg zum 8. Wegpunkt, um 180° gedreht, dadurch hatte die X-Koordinate der Drohne eine Abweichung von 50px zum Wegpunkt.
Habe den Wegpunkt jetzt einfach um 50px nach links verschoben.
