### ISSUE TITLE
Accountsystem über Webserver

### ISSUE THREAD

**Issue by MokkaGnom** [DronesTowerDefence/DTD#37]
Nutzer können sich mit
- Nutzername,
- E-Mail,
- Passwort,
registrieren. Dann würde im Multiplayer auch der entsprechende Nutzername angezeigt werden.

**Comment by MokkaGnom** [comment]
Funktionen:
- Freunde
- Passwort ändern
- Nutzername ändern (1x pro Monat)
- Spielstats (Anzahl der Spiele, Spielzeit, Datum des ersten Spiels, Datum des letzten Spiels)

**Comment by kelp-byte** [comment]
- Account löschen
- Premium Account mieten (1,72€ pro Monat)
- Ingame-Käufe (Skins)
- IngameShop-Verknüpfung
