### ISSUE TITLE
Neue INNOVATIVE Ideen

### ISSUE THREAD

**Issue by kelp-byte** [DronesTowerDefence/DTD#41]
Überlegt euch mal coole Sachen

-bspw. Tageszeiten die bestimmte Türme aussetzen lassen? (Strategien)
-Easter Eggs?
-Competetive Online Events? (Scores hochladen, Scoreboard)
-Saisonale Events? (Oster Event mit neuen Skins für Türme und Drohnen, etc)
-Mobile Version?
#30 - Neue Türme (Einfach da rein) z.B. Türme, die nach einigen Runden zerstört werden
-Archievements?
-Challenges (Müssen nicht Daily sein) bspw. könnte der teuerste Turm immer zerstört werden
-Map Creator, der Spieler Maps erstellen lässt)

**Comment by MokkaGnom** [comment]
Easter eggs, Achievements, mobile Version und Map creator finde ich gut.
Mobile Version und Map creator könnte @Daniel-0805 machen?

**Comment by MokkaGnom** [comment]
Map creator und mobile Version ist relativ unrealistisch.
Um easter eggs würde ich mich bei genügend Zeit noch kümmern.

**Comment by kelp-byte** [comment]
> Skilltree

Ähm. Ok.

**Comment by MokkaGnom** [comment]
Projekt Abgabe heute, was wir nicht umgesetzt haben, wird auch in Zukunft sehr wahrscheinlich nicht umgesetzt werden.
