### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by MokkaGnom** [DronesTowerDefence/DTD#47]
Sammeln aller Ideen für Achievements:
Name, Anforderung, Belohnung(Exp)

**Comment by MokkaGnom** [comment]
1000 Drohnen zerstört.

**Comment by MokkaGnom** [comment]
10000 Drohnen zerstört.

**Comment by MokkaGnom** [comment]
- 500 Türme platziert
- 1000 Türme platziert

**Comment by MokkaGnom** [comment]
- 100000 Geld ausgegeben.
- 500000 Geld ausgegeben.

**Comment by MokkaGnom** [comment]
- 100 Upgrades gekauft
- 300 Upgrades gekauft

**Comment by MokkaGnom** [comment]
- 10 Siege
- 50 Siege
- 100 Siege

**Comment by MokkaGnom** [comment]
- 20 Matches gespielt
- 80 Matches gespielt
- 120 Matches gespielt

**Comment by MokkaGnom** [comment]
- 10 Multiplayer Matches gespielt
- 30 Multiplayer Matches gespielt
- 60 Multiplayer Matches gespielt

**Comment by MokkaGnom** [comment]
- Jede Turm-Art in einem Match platziert
- Nur eine Turm-Art in einem Match platziert

**Comment by MokkaGnom** [comment]
- 1000 Geld in einem Match generiert
- 5000 Geld in einem Match generiert
- 10.000 Geld in einem Match generiert

**Comment by MokkaGnom** [comment]
- 100 Türme verkauft
- 200 Türme verkauft
- 500 Türme verkauft

**Comment by MokkaGnom** [comment]
- 20 Moads zerstört
- 40 Moads zerstört
- 80 Moads zerstört

**Comment by MokkaGnom** [comment]
- 20x das Spiel gestartet
- 40x das Spiel gestartet
- 80x das Spiel gestartet

**Comment by MokkaGnom** [comment]
c82c4c1:
- AchievementGUI fertig
- Achievements 1-10 implementiert
- Aktualisierte XP an Server gesendet

**Comment by MokkaGnom** [comment]
Vortschrittsanzeige fertig

**Comment by kelp-byte** [comment]
@MokkaGnom .

**Comment by MokkaGnom** [comment]
bb8baaeff1cd977fa1babad67bb4c9ba4d976814
8a94ccd409abdc70ce9864e6fd5af792b6fff8de

**Comment by MokkaGnom** [comment]
Dailys gemacht:
- 5
- 10
- 30
