### ISSUE TITLE
Wenn das Pause-Menü aufgerufen wird verschwindet die Musik

### ISSUE THREAD

**Issue by MokkaGnom** [DronesTowerDefence/DTD#50]
Sobald das Pause Menü einmal aufgerufen wird, ohne das dabei etwas verändert wird, ist die Musik stumm.

**Comment by SILVERFIELD19** [comment]
Kann keinen Fehler entdecken

**Comment by MokkaGnom** [comment]
Ja, stimmt, der Fehler liegt wo anders.
Die Musikeinstellung wird vom Anfang nicht richtig geladen, sondern erst, wenn man das Pause-Menü einmal aufruft.

Wenn z.B. in der Datei die Musik bei 0% gespeichert ist und man dann ein Spiel startet, ist die Musik trotzdem bei dem Standartwert (33% glaube). Erst wenn man dann das Pause-Menü einmal aufruft, wird die Einstellung aus der Datei genommen.
