### ISSUE TITLE
Achievement 13 wird noch nicht synchronisiert

### ISSUE THREAD

**Issue by MokkaGnom** [DronesTowerDefence/DTD#61]
Achievement wird gesendet aber vom Server nicht verarbeitet.

**Comment by kelp-byte** [comment]
@MokkaGnom Ich kann ohne Probleme ID 13 angeben und die über ein Testprogramm eintragen lassen? Guck mal bitte nach, was du sendest. Bis jetzt sind noch keine Einträge mit ID 13 dort.

**Comment by kelp-byte** [comment]
Und es gibt ein Eintrag mit ID 15, wieso auch immer.

**Comment by MokkaGnom** [comment]
Ja, habe den Fehler gefunden, die Achievements wurden nur gesendet, wenn der erste Meilenstein erreicht wurde. Habe das jetzt geändert.
