### ISSUE TITLE
Beim Verlieren kommt der Pause Screen

### ISSUE THREAD

**Issue by Daniel-0805** [DronesTowerDefence/DTD#73]

**Comment by kelp-byte** [comment]
Hier hat jemand wohl den Namen einer PauseMenu-Methode falsch interpretiert, da in der Game::checkLost einfach das PauseMenu aufgerufen wird mit (true). Weiß nicht, wieso oder warum, aber joa. Ich habe das jz mal auskommentiert, sollte gleich behoben sein.
