### ISSUE TITLE
Credits mit Taste abbrechen

### ISSUE THREAD

**Issue by kelp-byte** [DronesTowerDefence/DTD#74]
Ich weiß nicht, welche, aber die TAsten, die üblicherweise sowas abbrechen (Enter oder Escape) funktionieren nicht, die Credits laufen unendlich weiter.

**Comment by kelp-byte** [comment]
NVM, Doppelklick funkt jz, aber wäre cool, wenn man ESC oder jede Taste zum abbrechen drücken könnte.

**Comment by MokkaGnom** [comment]
Kann mit esc geschlossen werden.
