### ISSUE TITLE
settings.sav führt (unregelmäßig) zu einem Fehler

### ISSUE THREAD

**Issue by Daniel-0805** [DronesTowerDefence/DTD#77]

**Comment by Daniel-0805** [comment]
Wir haben es erstmal auskommentiert. @kelp-byte: Wenn du dich drum kümmern möchtest, kannst du das machen

**Comment by kelp-byte** [comment]
> Wir haben es erstmal auskommentiert. @kelp-byte: Wenn du dich drum kümmern möchtest, kannst du das machen

Ungern, der Fehler hat keine logische Ursache. Da sucht man sich tot. so ist genug. Außerdem erstelle ich einen Tag für neue Sachen nach der Abgabe

**Comment by MokkaGnom** [comment]
Das label ist theoretisch unnötig, da das schon deutlich durch das Projekt wird.

**Comment by kelp-byte** [comment]
Das Label ist übersichtlicher als Abgrenzung, was neu dazukommt.

**Comment by Daniel-0805** [comment]
zweite Zeile der Datei wird ignoriert

**Comment by MokkaGnom** [comment]
> zweite Zeile der Datei wird ignoriert

Ok, gucke ich mir am WE mal an.
